### ISSUE TITLE
Provide an option to disable SSL cert verification when connecting to remote server.

### ISSUE THREAD

**Issue by qingvincentyin** [GoogleCloudPlatform/pubsub2inbox#78]
I followed:

- https://taneli-leppa.medium.com/synchronizing-containers-from-jfrog-artifactory-to-google-cloud-artifact-registry-5346a13c5808

My JFrog Artifactory is listening on a **private IP** only. It is an internal JFrog installation in an enterprise and not meant to be exposed on a public IP. As such, my JFrog's SSL cert (or, more accurately, the cert for its Nginx proxy) is a self-signed cert (or, equivalently, a cert signed by my enterprise's internal/private Root CA). It is not signed by a well-known Root CA. This is a legit usage of self-signed cert.

I got this error:
```python
  Traceback (most recent call last):
    File "/workspace/main.py", line 768, in process_message_pipeline
      processor_variables = processor_instance.process()
    File "/workspace/processors/docker.py", line 95, in process
      source_registry = Registry(hostname=hostname,
    File "/workspace/_vendor/python_docker/registry.py", line 25, in __init__
      self.detect_authentication()
    File "/workspace/_vendor/python_docker/registry.py", line 29, in detect_authentication
      response = requests.get(f"{self.hostname}/v2/")
    File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/api.py", line 73, in get
      return request("get", url, params=params, **kwargs)
    File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/api.py", line 59, in request
      return session.request(method=method, url=url, **kwargs)
    File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
      resp = self.send(prep, **send_kwargs)
    File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
      r = adapter.send(request, **kwargs)
    File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
      raise SSLError(e, request=request)
  requests.exceptions.SSLError: HTTPSConnectionPool(host='10.55.60.2', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
```

The root cause is this line:

- https://github.com/GoogleCloudPlatform/pubsub2inbox/blob/d3e8ccd806300c4538951f9c0102a3f0e1905bc8/_vendor/python_docker/registry.py#L29

```python
    def detect_authentication(self):
        response = requests.get(f"{self.hostname}/v2/")
```

Now, `requests.get()` in general accepts an optional 2nd param such as:
```python
requests.get("https://example.com", verify=False)
```

But your code doesn't pass any 2nd param; therefore, your code doesn't give the option to ignore SSL cert verification (e.g., for self-signed cert.)

I recommend that your code be modified to accept the 2nd optional param `verify=[True | False]` so that the user has a choice.

P.S. Alternatively, if GCP Cloud Functions provides a way for a user to install an SSL cert, it would solve the problem, too. But I cannot find such a way.

**Comment by rosmo** [comment]
Could you give the code here a try: https://github.com/GoogleCloudPlatform/pubsub2inbox/pull/79

I added two flags: `tls_verify` for source repository and `destination_tls_verify` for target repository.

**Comment by qingvincentyin** [comment]
I'm very impressed with your fast help! Beyond my expectations, thank you!

Consider this line

- https://github.com/GoogleCloudPlatform/pubsub2inbox/blob/51422dd7b5d81fab7866cabc64462770363587cf/examples/artifactory-to-artifact-registry/main.tf#L104

I modified the surrounding Terraform so that the `config` YAML content now looks like this (notice the 2 lines of `tls_verify: false`):
```yaml
# Synchronize changes from Artifactory Docker registry into Google Cloud
# Artifact Registry
pipeline:
  - type: processor.genericjson
  - type: output.logger
    config:
      message: |
        Webhook details: {{ data }}

  - type: processor.docker
    runIf: "{% if data.event_type == 'pushed' %}1{% endif %}"
    config:
      mode: image.copy
      hostname: "{{ data.jpd_origin }}"
      username: "******"
      password: "******"
      image: "{{ data.data.repo_key }}/{{ data.data.image_name }}"
      tag: "{{ data.data.tag }}"
      destination_hostname: "https://us-east4-docker.pkg.dev"
      destination_image: "my-********-prj/pubsub2inbox/{{ data.data.image_name }}"
      tls_verify: false

  - type: processor.docker
    runIf: "{% if data.event_type == 'deleted' %}1{% endif %}"
    config:
      mode: image.deleteversion
      hostname: "https://us-east4-docker.pkg.dev"
      image: "my-********-prj/pubsub2inbox/{{ data.data.image_name }}"
      tag: "{{ data.data.tag }}"
      tls_verify: false
```

Then, when your Cloud Function is triggered by JFrog's webhook, I got this error:
```python
Traceback (most recent call last):
  File "/workspace/main.py", line 768, in process_message_pipeline
    processor_variables = processor_instance.process()
  File "/workspace/processors/docker.py", line 99, in process
    source_tls_verify = self._jinja_expand_bool(self['tls_verify'],
TypeError: 'DockerProcessor' object is not subscriptable
```

At this point, I need your help. It would take me too long to read and understand your Python program's logic in order to debug this. It'll be a lot easier (perhaps even obvious) for you to figure it out, I think.

Better yet, if you can add the necessary Terraform change (in `/pubsub2inbox/examples/artifactory-to-artifact-registry/`) to your PR so that it is a complete, end-to-end working code, it'll make life a lot easier for me and all future users.

P.S. I `terraform destroy` followed by `terraform create` to ensure my installation is clean. I further verified in GCP Console that the deployed Cloud Functions is indeed the new version in your PR:

![image](https://github.com/user-attachments/assets/a437a23f-60ac-444b-994a-96306f2aacef)

**Comment by rosmo** [comment]
Looks like I made a small mistake there (I have a bit of hard time testing as I don't have the test environment around anymore). I pushed a fix to it, would you be able to retry with that? If it doesn't still work, I'll try to find some time to set up a testing environment.

**Comment by qingvincentyin** [comment]
I now get this error:
```python
Traceback (most recent call last):
  File "/workspace/main.py", line 768, in process_message_pipeline
    processor_variables = processor_instance.process()
  File "/workspace/processors/docker.py", line 107, in process
    source_registry = Registry(hostname=hostname,
  File "/workspace/_vendor/python_docker/registry.py", line 26, in __init__
    self.detect_authentication()
  File "/workspace/_vendor/python_docker/registry.py", line 32, in detect_authentication
    response = requests.get(f"{self.hostname}/v2/")
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/adapters.py", line 595, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.10.10.10', port=443): 
    Max retries exceeded with URL: 
            /v2/ (Caused by SSLError(SSLCertVerificationError(1, 
            '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
```

Comparing that with my original stack trace (before your PR), I see:

- The new stack trace's line numbers match the source code of your PR. That means I'm running the correct version of your PR code.
- The 2 stack traces differ in the bottom (most recent) call's line number. The original was `adapter.py, line 517` while the newest is `adapters.py, line 595`. That means your PR made some difference but not enough.

**Comment by rosmo** [comment]
I set up a test environment and did some fixes. Could you try the latest code from the PR?

**Comment by qingvincentyin** [comment]
It works!
I just successfully tested both adding and deleting a Docker image from JFrog. Your code auto-synced successfully to GAR.

After you merge your PR, I plan to submit a new PR to expand the terraform code in `/pubsub2inbox/examples/artifactory-to-artifact-registry/` to include the optional param `tls_verify`. That'll make it a complete end-to-end example.

**Comment by rosmo** [comment]
Great to hear! I just merged my PR. The `verify` parameter also accepts a string (that points to a CA bundle file)a and I've now added a function if that you can pass both boolean-like variables (to set verify=False) and also strings, which would point to your CA bundle (you'd probably want to bundle a recent `ca-bundle.crt` from a distro (eg. https://packages.debian.org/bookworm/ca-certificates) and append your own certificate to that).

**Comment by qingvincentyin** [comment]
I believe that if the param is passed like:

- `requests.get(..., verify='/etc/ssl/certs/ca-certificates.crt'`)

then the file path refers to the runtime server-side filesystem, i.e., the runtime filesystem of the Cloud Functions' Docker container. It doesn't refer to (or somehow upload from) my laptop's filesystem at the time of `terraform apply`. So, I don't think that `verify` param by itself can do the trick.

However, using your idea as a starting point, I suppose a more complex logic can be written into your Python code so that it accepts the content (not just a filename) of a cert file, dynamically (at runtime) saves it to somewhere like `/tmp/my-cert.crt` (on the runtime Docker container's filesystem), then do `verify=/tmp/my-cert.crt`. Just a preliminary thought.

**Comment by qingvincentyin** [comment]
I submitted the Terraform PR ^^^.

**Comment by qingvincentyin** [comment]
I harden the solution better for an enterprise environment, I submitted a new PR to work with VPC Service Control perimeter:

- https://github.com/GoogleCloudPlatform/pubsub2inbox/pull/83

Could you review it, please?
